var CONSUMER_KEY = "qDPSgsoNVApZMrYuF8HujhzhC";
exports.CONSUMER_KEY = CONSUMER_KEY;
var CONSUMER_SECRET = "8OqHRjx4Kk6P3UP3cNSszzYo5jGp1LAOnNkoPD5ZCqSVKIjxrf";
exports.CONSUMER_SECRET = CONSUMER_SECRET;
var  ACCESS_TOKEN_KEY = "3038903372-rbdF8tZ09omaSBybQ8MKNZPjq4qchkGrYp2OgwY";
exports.ACCESS_TOKEN_KEY = ACCESS_TOKEN_KEY;
var ACCESS_TOKEN_SECRET = "oEMjhhDfdEI9XBZe8aNCVuGYhRhe0I7upY62c3FoerWX0";
exports.ACCESS_TOKEN_SECRET = ACCESS_TOKEN_SECRET;
